name: priors
channels:
  - conda-forge
dependencies:
  - h5py=3.10.0
  - jupyter=1.0.0
  - numpy=1.26.3
  - pip=23.3.2
  - python=3.9.18
  - pip:
    - --find-links https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
    - datasets==2.16.1
    - dawgz==0.5.2
    - inox==0.5.0
    - jax[cuda11_pip]==0.4.23
    - matplotlib==3.8.2
    - nvidia-cudnn-cu11~=8.9
    - optax==0.1.7
    - POT==0.9.3
    - scipy==1.12.0
    - tqdm==4.66.1
    - wandb==0.16.2
  - pip:
    - torch==2.2.2
    - torchvision==0.17.2
    - torch-fidelity==0.3.0
